Pr test
viseo-asia/school-digital pull request #3
Opened 2021-05-13 09:00 UTC by DidierHoarauVISEO

2021-05-13 09:00 UTC, DidierHoarauVISEO commented
Can one of the admins verify this patch?

2021-05-13 09:00 UTC, DidierHoarauVISEO commented
Can one of the admins verify this patch?

2021-05-14 01:53 UTC, DidierHoarauVISEO reviewed
Build Failed

2021-05-14 02:23 UTC, VISEO-DevOps requested changes
Build Failed

2021-05-14 02:57 UTC, VISEO-DevOps reviewed
Build Successful: demoapp-news:1.0.0

2021-05-14 03:03 UTC, VISEO-DevOps approved these changes
Build Successful: demoapp-news:1.0.0

2021-05-14 03:06 UTC, VISEO-DevOps requested changes
PR Failed. Build Failed: demoapp-news:1.0.0

2021-05-14 03:08 UTC, VISEO-DevOps approved these changes
Build Successful: demoapp-news:1.0.0

2021-05-16 22:42 UTC, VISEO-DevOps requested changes
PR Failed. Build Failed: demoapp-news:1.0.0

2021-05-16 22:48 UTC, VISEO-DevOps approved these changes
Build Successful: demoapp-news:1.0.0

2021-05-16 22:51 UTC, VISEO-DevOps approved these changes
Build Successful: demoapp-news:1.0.0

2021-05-19 01:00 UTC, closed without merging

2021-05-19 01:01 UTC, VISEO-DevOps approved these changes
Build Successful: demoapp-news:1.0.0